/**
 * CurseGuard lexicon — English profanity / NSFW terms.
 * Sorted longest-first at runtime so multi-word phrases match first.
 * Intentionally omits high false-positive tokens (e.g. "hell", "sex", "class").
 */

export const PROFANITY_WORDS: string[] = [
  "son of a bitch",
  "piece of shit",
  "glory hole",
  "doggy style",
  "sand nigger",
  "camel jockey",
  "white trash",
  "trailer trash",
  "mother fucker",
  "motherfucker",
  "motherfuckers",
  "motherfucking",
  "motherfucked",
  "cocksucker",
  "cocksuckers",
  "cocksucking",
  "cock sucker",
  "circle jerk",
  "gang bang",
  "blow job",
  "jack off",
  "jerk off",
  "dumb ass",
  "dipshit",
  "dipshits",
  "bullshit",
  "bullshits",
  "bullshitting",
  "bullshitted",
  "horseshit",
  "chickenshit",
  "apeshit",
  "batshit",
  "jackass",
  "jackasses",
  "dumbass",
  "dumbasses",
  "smartass",
  "smartasses",
  "hardass",
  "badass",
  "badasses",
  "kickass",
  "kissass",
  "asshole",
  "assholes",
  "asshat",
  "asswipe",
  "asswipes",
  "assclown",
  "asslicker",
  "assfuck",
  "arsehole",
  "arseholes",
  "shithead",
  "shitheads",
  "shitface",
  "shitbag",
  "shitbags",
  "shitshow",
  "shitstorm",
  "shitstain",
  "shithole",
  "shithouse",
  "shitload",
  "shitless",
  "shitass",
  "shitty",
  "shittier",
  "shittiest",
  "shitting",
  "shitted",
  "shits",
  "shit",
  "fuckboy",
  "fuckboys",
  "fuckwit",
  "fuckwits",
  "fuckface",
  "fuckhead",
  "fuckheads",
  "fucktard",
  "fucktards",
  "fuckery",
  "fuckers",
  "fucker",
  "fucking",
  "fuckin",
  "fucked",
  "fucks",
  "fuck",
  "clusterfuck",
  "mindfuck",
  "ratfuck",
  "shitfuck",
  "buttfuck",
  "buttfucker",
  "fistfuck",
  "dumbfuck",
  "dumbfucks",
  "shitforbrains",
  "faggot",
  "faggots",
  "faggit",
  "fagtard",
  "bastards",
  "bastard",
  "bitches",
  "bitching",
  "bitchy",
  "bitched",
  "bitch",
  "bollocks",
  "bollock",
  "bugger",
  "buggers",
  "buggering",
  "buggery",
  "goddamn",
  "goddamned",
  "goddammit",
  "goddamnit",
  "damn it",
  "dammit",
  "damnit",
  "damned",
  "damn",
  "cunts",
  "cunt",
  "twats",
  "twat",
  "dickhead",
  "dickheads",
  "dickwad",
  "dickweed",
  "dickface",
  "dickbag",
  "dicks",
  "dick",
  "cockblock",
  "cocks",
  "cock",
  "penis",
  "penises",
  "vagina",
  "vaginas",
  "pussies",
  "pussy",
  "boobs",
  "boobies",
  "titties",
  "tits",
  "titty",
  "butthole",
  "buttholes",
  "buttplug",
  "blowjob",
  "blowjobs",
  "handjob",
  "handjobs",
  "rimjob",
  "rimjobs",
  "fellatio",
  "cunnilingus",
  "orgasm",
  "orgasms",
  "ejaculate",
  "ejaculation",
  "masturbate",
  "masturbating",
  "masturbation",
  "masturbated",
  "horny",
  "pornography",
  "pornographic",
  "porno",
  "porns",
  "porn",
  "hentai",
  "onlyfans",
  "camgirl",
  "cuckold",
  "bdsm",
  "slutty",
  "sluts",
  "slut",
  "whores",
  "whore",
  "hooker",
  "hookers",
  "prostitute",
  "prostitutes",
  "prostitution",
  "stripper",
  "strippers",
  "milf",
  "dilf",
  "threesome",
  "foursome",
  "orgy",
  "orgies",
  "incest",
  "incestuous",
  "pedophile",
  "pedophiles",
  "pedophilia",
  "paedophile",
  "molester",
  "molestation",
  "rapist",
  "rapists",
  "raping",
  "raped",
  "cumshot",
  "cumshots",
  "creampie",
  "bukkake",
  "dildo",
  "dildos",
  "ballsack",
  "boner",
  "boners",
  "hard-on",
  "hardon",
  "wanker",
  "wankers",
  "wanking",
  "wank",
  "tosser",
  "tossers",
  "douchebag",
  "douchebags",
  "douche",
  "pissed",
  "pisses",
  "pissing",
  "pissoff",
  "piss",
  "crappy",
  "turd",
  "turds",
  "ass",
  "asses",
  "arse",
  "arses",
  "craphead",
  "jizz",
  "jizzed",
  "smegma",
  "queef",
  "queefs",
  "fisting",
  "deepthroat",
  "deepthroating",
  "facesitting",
  "strap-on",
  "strapon",
  "gloryhole",
  "gangbang",
  "gangbangs",
  "bareback",
  "barebacking",
  "doggystyle",
  "wetback",
  "wetbacks",
  "beaner",
  "beaners",
  "chink",
  "chinks",
  "gook",
  "gooks",
  "kike",
  "kikes",
  "nigger",
  "niggers",
  "nigga",
  "niggas",
  "niggah",
  "darkie",
  "darkies",
  "towelhead",
  "towelheads",
  "raghead",
  "ragheads",
  "retard",
  "retards",
  "retarded",
  "dykes",
  "dyke",
  "tranny",
  "trannies",
  "shemale",
  "shemales",
  "fags",
  "fag",
];

/** Common leetspeak / obfuscation substitutions */
const LEET_MAP: Record<string, string> = {
  a: "[a@4áàâäã]",
  b: "[b8]",
  c: "[cç(]",
  e: "[e3éèêë]",
  g: "[g9]",
  i: "[i1!|íìîï]",
  l: "[l1|]",
  o: "[o0óòôöõ]",
  s: "[s5$z]",
  t: "[t7+]",
  u: "[uúùûü]",
  y: "[yýÿ]",
};

/**
 * Build a regex source that matches a word with optional leetspeak and
 * light separator insertion (f.u.c.k, f-u-c-k, f_u_c_k).
 */
export function wordToPattern(word: string, aggressive: boolean): string {
  const normalized = word.toLowerCase().trim();
  if (!normalized) return "";

  const parts = normalized.split(/\s+/);

  const segmentPatterns = parts.map((segment) => {
    const chars = segment.split("");
    const charPatterns = chars.map((ch, idx) => {
      const leet = LEET_MAP[ch] ?? escapeRegex(ch);
      if (aggressive && idx < chars.length - 1) {
        return `${leet}[+\\-_.\\s*]*`;
      }
      return leet;
    });
    return charPatterns.join("");
  });

  return segmentPatterns.join("[\\s\\-_]+");
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

let _sorted: string[] | null = null;

export function getSortedWords(): string[] {
  if (!_sorted) {
    _sorted = [...PROFANITY_WORDS].sort((a, b) => b.length - a.length);
  }
  return _sorted;
}

export function buildProfanityRegex(aggressive: boolean): RegExp {
  const words = getSortedWords();
  const patterns = words
    .map((w) => wordToPattern(w, aggressive))
    .filter(Boolean);
  const body = patterns.join("|");
  return new RegExp(`(?<![a-zA-Z0-9])(?:${body})(?![a-zA-Z0-9])`, "gi");
}
